-- MySQL Script generated by MySQL Workbench
-- 05/24/18 14:58:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rol_en_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol_en_sistema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `nombreReferencia` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `tipoDocumento` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rol_idx` (`rol` ASC),
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`Rol_en_sistema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `idDirector` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relacion_profesor_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relacion_profesor_departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProfesor` INT NOT NULL,
  `idDepartamento` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  `intensidadHoraria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profesor_idx` (`idProfesor` ASC),
  INDEX `fk_departamento_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_profesor_departamento`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `mydb`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamento_profesor`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idLider` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `areaConocimiento` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `ultimaClasificacion` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `clasificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lider_idx` (`idLider` ASC),
  CONSTRAINT `fk_lider`
    FOREIGN KEY (`idLider`)
    REFERENCES `mydb`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Revista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rank` VARCHAR(45) NULL,
  `nombre` VARCHAR(85) NULL,
  `tipo` VARCHAR(45) NULL,
  `issn` VARCHAR(45) NULL,
  `sjr` VARCHAR(45) NULL,
  `cuartilScopus` VARCHAR(45) NULL,
  `cuartilIsci` VARCHAR(45) NULL,
  `cuartilIndex` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoArticulo` VARCHAR(45) NOT NULL,
  `tituloArticulo` VARCHAR(200) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `paginaInicial` INT NULL,
  `paginaFinal` INT NULL,
  `idioma` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `fechaup` DATE  NULL,
  `idRevista` INT NULL,
  `volumen` INT NULL,
  `fasciculoRevista` VARCHAR(45) NULL,
  `serieRevista` INT NULL,
  `medioDivulgacion` VARCHAR(45) NULL,
  `sitioWeb` VARCHAR(200) NULL,
  `doi` VARCHAR(200) NULL,
  `estado` VARCHAR(45) NULL,
  `cuartilScopus` VARCHAR(45) NULL,
  `cuartilIsci` VARCHAR(45) NULL,
  `cuartilIndex` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_revista_idx` (`idRevista` ASC),
  CONSTRAINT `fk_revista`
    FOREIGN KEY (`idRevista`)
    REFERENCES `mydb`.`Revista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relacion_profesor_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relacion_profesor_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProfesor` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profesor_idx` (`idProfesor` ASC),
  INDEX `fk_grupo_idx` (`idGrupo` ASC),
  CONSTRAINT `fk_profesor_grupo`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `mydb`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_profesor`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `mydb`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relacion_profesor_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relacion_profesor_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProfesor` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profesor_idx` (`idProfesor` ASC),
  INDEX `fk_producto_idx` (`idProducto` ASC),
  CONSTRAINT `fk_profesor_producto`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `mydb`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_profesor`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
